In [1]:
import pandas as pd

    loc
    iloc

In [3]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s2 = pd.Series([10,20,30,40,50] , index = ["A","B","C","D","E"])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [7]:
s.iloc[0]

np.int64(10)

In [8]:
s.iloc[-1]

np.int64(50)

In [9]:
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [10]:
s2.iloc[0]

np.int64(10)

In [11]:
s2.loc["B"]

np.int64(20)

In [12]:
s2.loc["A":"D"]

A    10
B    20
C    30
D    40
dtype: int64

In [13]:
s2.loc["A":"D":2]

A    10
C    30
dtype: int64

In [14]:
s2.loc[::-1]

E    50
D    40
C    30
B    20
A    10
dtype: int64

In [20]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [16]:
s.mean()

np.float64(30.0)

In [17]:
s.max()

50

In [18]:
s.min()

10

In [28]:
s.argmax()  # return index of maximum value

np.int64(4)

In [29]:
s.argmin()

np.int64(0)

# ***`DataFrame`***
    Collection of series
    2D
    collection of different type of data(hetrogeneous data structure)

    using dictionary

In [31]:
pd.DataFrame({
    "Name" : ["simran" , "Deep" , "gaurav"] ,
    "Age"  : [23 , 24 , 23] ,
    "Address" : ["Jaipur" , "Delhi" , "Ajmer"],
    "Marks" : [20 , 23 , 21],
})

     Name  Age Address  Marks
0  simran   23  Jaipur     20
1    Deep   24   Delhi     23
2  gaurav   23   Ajmer     21

In [34]:
pd.DataFrame({
    "Name" : ["Garvita" , "Ayushi" , "Asha" , "Kavya" , "Riya"] ,
    "Age" : [20,23,19,25,18] , 
    "Percentage" : ["99%" , "98%" , "92%" , "85%" , "82%"],
    "Height" : ["5'3" , "5'9" , "5'2" , "5'8" , "4'9"]
})

      Name  Age Percentage Height
0  Garvita   20        99%    5'3
1   Ayushi   23        98%    5'9
2     Asha   19        92%    5'2
3    Kavya   25        85%    5'8
4     Riya   18        82%    4'9

    using list of list(rows and columns)

In [37]:
pd.DataFrame([
    ["rohan" , 22 , 21],
    ["Aman" , 23 , 20]
], columns = ["Name" , "Marks" , "Age"])

    Name  Marks  Age
0  rohan     22   21
1   Aman     23   20

In [38]:
import numpy as np

In [78]:
data = pd.DataFrame({
    "Height" : np.random.normal(140 , 10 , 10) ,
    "Weight" : np.random.normal(60 , 10 , 10) ,
    "Salary" : np.random.normal(50000 , 10000 , 10) ,
    "Age" : np.random.normal(20 , 4 , 10).astype(int) ,
    "Gender" : np.random.choice(["Male" , "Female"] , size = 10) , 
    "Country" : np.random.choice(["India", "USA", "UK", "Germany", "Japan"] , 10)
})
data

       Height     Weight        Salary  Age  Gender Country
0  154.284007  66.349059  54285.601062   21  Female   Japan
1  144.686198  50.038510  60727.209276   18  Female   India
2  144.016207  45.888431  40047.952601   23  Female   Japan
3  145.736573  71.259845  68032.382051   18  Female      UK
4  138.452614  82.399652  42557.819046   22    Male   Japan
5  157.006184  64.243415  54828.198217   17    Male   Japan
6  152.733362  68.366597  62977.828456   23  Female   Japan
7  150.199143  59.253094  60269.053065   21    Male   India
8  149.659388  68.111621  53986.716092   25    Male      UK
9  130.843729  53.825316  47520.701533   20  Female   India

In [59]:
data["Height"]

0    143.059718
1    142.334609
2    147.919361
3    126.261287
4    141.500122
5    144.974078
6    146.295813
7    128.918062
8    121.896569
9    148.806071
Name: Height, dtype: float64

In [63]:
a = data["Weight"]

In [61]:
data["Salary"]

0    41331.866003
1    41174.689142
2    49639.485223
3    41395.774311
4    50470.386865
5    42002.222384
6    24777.254889
7    43611.959509
8    44615.448658
9    50032.060834
Name: Salary, dtype: float64

In [84]:
data["Bonus"] = data["Salary"] * 0.20
data

       Height     Weight        Salary  Age  Gender Country         Bonus
0  154.284007  66.349059  54285.601062   21  Female   Japan  10857.120212
1  144.686198  50.038510  60727.209276   18  Female   India  12145.441855
2  144.016207  45.888431  40047.952601   23  Female   Japan   8009.590520
3  145.736573  71.259845  68032.382051   18  Female      UK  13606.476410
4  138.452614  82.399652  42557.819046   22    Male   Japan   8511.563809
5  157.006184  64.243415  54828.198217   17    Male   Japan  10965.639643
6  152.733362  68.366597  62977.828456   23  Female   Japan  12595.565691
7  150.199143  59.253094  60269.053065   21    Male   India  12053.810613
8  149.659388  68.111621  53986.716092   25    Male      UK  10797.343218
9  130.843729  53.825316  47520.701533   20  Female   India   9504.140307

In [85]:
data

       Height     Weight        Salary  Age  Gender Country         Bonus
0  154.284007  66.349059  54285.601062   21  Female   Japan  10857.120212
1  144.686198  50.038510  60727.209276   18  Female   India  12145.441855
2  144.016207  45.888431  40047.952601   23  Female   Japan   8009.590520
3  145.736573  71.259845  68032.382051   18  Female      UK  13606.476410
4  138.452614  82.399652  42557.819046   22    Male   Japan   8511.563809
5  157.006184  64.243415  54828.198217   17    Male   Japan  10965.639643
6  152.733362  68.366597  62977.828456   23  Female   Japan  12595.565691
7  150.199143  59.253094  60269.053065   21    Male   India  12053.810613
8  149.659388  68.111621  53986.716092   25    Male      UK  10797.343218
9  130.843729  53.825316  47520.701533   20  Female   India   9504.140307

In [88]:
data.describe()   # statistics summary

           Height     Weight        Salary        Age         Bonus
count   10.000000  10.000000     10.000000  10.000000     10.000000
mean   146.761740  62.973554  54523.346140  20.800000  10904.669228
std      7.836715  10.910118   8991.716595   2.573368   1798.343319
min    130.843729  45.888431  40047.952601  17.000000   8009.590520
25%    144.183705  55.182261  49137.205173  18.500000   9827.441035
50%    147.697981  65.296237  54556.899639  21.000000  10911.379928
75%    152.099807  68.302853  60612.670223  22.750000  12122.534045
max    157.006184  82.399652  68032.382051  25.000000  13606.476410