In [1]:
import seaborn as sns

In [3]:
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [5]:
data["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [6]:
data["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [7]:
data["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [8]:
data["tip"].value_counts()

tip
2.00    33
3.00    23
4.00    12
5.00    10
2.50    10
        ..
4.34     1
1.56     1
5.20     1
2.60     1
1.75     1
Name: count, Length: 123, dtype: int64

In [9]:
data["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [13]:
data["total_bill"].max()

50.81

In [14]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
# Highest smoker of which sex?
# highest tip of what amount?
# At what time people arrive the most?
# Maximum size a person take with themself?
# At what time male arrive the most?
# At which day people arrive the least?
# How many people arrive on Thrusday?
# At which day male arrive the most?
# At what time on saturday people arrive the most?
# At what time usually the smoker arrives?

    Female total average bill

In [16]:
data[data["sex"]=="Female"]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [19]:
data[data["sex"]=="Female"]["total_bill"]

0      16.99
4      24.59
11     35.26
14     14.83
16     10.33
       ...
226    10.09
229    22.12
238    35.83
240    27.18
243    18.78
Name: total_bill, Length: 87, dtype: float64

In [20]:
data[data["sex"]=="Female"]["total_bill"].mean()

np.float64(18.056896551724133)

    max of total bill

In [21]:
data["total_bill"].max()

50.81

In [22]:
data["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
data[data["day"]=="Sun"]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [30]:
data["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [31]:
(data["size"]==2).sum()

np.int64(156)

    male / female average tip

In [35]:
data[data["sex"]=="Female"]["tip"].mean()

np.float64(2.8334482758620685)

In [37]:
data[data["sex"]=="Male"]["tip"].mean()

np.float64(3.0896178343949043)

    Smoker male / female
    Smoker day

In [49]:
data[data["sex"]=="Female"]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [56]:
data[data["sex"]=="Female"][data["smoker"]=="Yes"]

C:\Users\DELL\AppData\Local\Temp\ipykernel_14564\1323291259.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data["sex"]=="Female"][data["smoker"]=="Yes"]

     total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
92         5.75  1.00  Female    Yes   Fri  Dinner     2
93        16.32  4.30  Female    Yes   Fri  Dinner     2
100       11.35  2.50  Female    Yes   Fri  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
164       17.51  3.00  Female    Yes   Sun  Dinner     2
168       10.59  1.61  Female    Yes   Sat  Dinner     2
169       10.63  2.00  Female    Yes   Sat  Dinner     2
178        9.60  4.00  Female    Yes   Sun  Dinner     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
188       18.15  3.50  Female    Yes   Sun  Dinner     3
191       19.81  4.19  Female    Yes  Thur   Lunch     2
197       43.11  5.00  Female    Yes  Thur   Lunch     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
201       12.74  2.01  Female    Yes  Thur   Lunch     2
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
205       16.47  3.23  Female    Yes  Thur   Lunch     3
209       12.76  2.23  Female    Yes   Sat  Dinner     2
213       13.27  2.50  Female    Yes   Sat  Dinner     2
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
221       13.42  3.48  Female    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [60]:
data[data["sex"]=="Female"][data["smoker"]=="Yes"].count()

C:\Users\DELL\AppData\Local\Temp\ipykernel_14564\442464844.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data["sex"]=="Female"][data["smoker"]=="Yes"].count()

total_bill    33
tip           33
sex           33
smoker        33
day           33
time          33
size          33
dtype: int64

In [75]:
data[data["sex"]=="Male"][data["smoker"]=="Yes"].count()

C:\Users\DELL\AppData\Local\Temp\ipykernel_14564\3574316456.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data["sex"]=="Male"][data["smoker"]=="Yes"].count()

total_bill    60
tip           60
sex           60
smoker        60
day           60
time          60
size          60
dtype: int64

In [62]:
data[(data["sex"]=="Male") & (data["smoker"]=="Yes")].shape[0]

60

In [63]:
data[(data["sex"]=="Female") & (data["smoker"]=="Yes")].shape[0]

33

In [66]:
data["day"].value_counts().index

CategoricalIndex(['Sat', 'Sun', 'Thur', 'Fri'], categories=['Thur', 'Fri', 'Sat', 'Sun'], ordered=False, dtype='category', name='day')

In [67]:
for i in data["day"].value_counts().index:
    print(i)

Sat
Sun
Thur
Fri

In [68]:
data[(data["smoker"]=="Yes") & (data["day"]=="Sat")].shape[0]

42

In [77]:
for i in data["day"].value_counts().index:
    print(f"{i} --> {data[(data["smoker"]=="Yes") & (data["day"]==i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15