In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [4]:
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Pivot table

In [5]:
data.pivot_table?

Signature:
data.pivot_table(
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Level' = 'All',
    observed: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
values : list-like or scalar, optional
    Column or columns to aggregate.
index : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table index. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
columns : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table column. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
aggfunc : function, list of functions, dict, default "mean"
    If a list of functions is passed, the resulting pivot table will have
    hierarchical columns whose top level are the function names
    (inferred from the function objects themselves).
    If a dict is passed, the key is column to aggregate and the value is
    function or list of functions. If ``margin=True``, aggfunc will be
    used to calculate the partial aggregates.
fill_value : scalar, default None
    Value to replace missing values with (in the resulting pivot table,
    after aggregation).
margins : bool, default False
    If ``margins=True``, special ``All`` columns and rows
    will be added with partial group aggregates across the categories
    on the rows and columns.
dropna : bool, default True
    Do not include columns whose entries are all NaN. If True,
    rows with a NaN value in any column will be omitted before
    computing margins.
margins_name : str, default 'All'
    Name of the row / column that will contain the totals
    when margins is True.
observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.

    .. deprecated:: 2.2.0

        The default value of ``False`` is deprecated and will change to
        ``True`` in a future version of pandas.

sort : bool, default True
    Specifies if the result should be sorted.

    .. versionadded:: 1.3.0

Returns
-------
DataFrame
    An Excel style pivot table.

See Also
--------
DataFrame.pivot : Pivot without aggregation that can handle
    non-numeric data.
DataFrame.melt: Unpivot a DataFrame from wide to long format,
    optionally leaving identifiers set.
wide_to_long : Wide panel to long format. Less flexible but more
    user-friendly than melt.

Notes
-----
Reference :ref:`the user guide <reshaping.pivot>` for more examples.

Examples
--------
>>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
...                          "bar", "bar", "bar", "bar"],
...                    "B": ["one", "one", "one", "two", "two",
...                          "one", "one", "two", "two"],
...                    "C": ["small", "large", "large", "small",
...                          "small", "large", "small", "small",
...                          "large"],
...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
>>> df
     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

This first example aggregates values by taking the sum.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                        columns=['C'], aggfunc="sum")
>>> table
C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

We can also fill missing values using the `fill_value` parameter.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                        columns=['C'], aggfunc="sum", fill_value=0)
>>> table
C        large  small
A   B
bar one      4      5
    two      7      6
foo one      4      1
    two      0      6

The next example aggregates by taking the mean across multiple columns.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                        aggfunc={'D': "mean", 'E': "mean"})
>>> table
                D         E
A   C
bar large  5.500000  7.500000
    small  5.500000  8.500000
foo large  2.000000  4.500000
    small  2.333333  4.333333

We can also calculate multiple types of aggregations for any given
value column.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                        aggfunc={'D': "mean",
...                                 'E': ["min", "max", "mean"]})
>>> table
                  D   E
               mean max      mean  min
A   C
bar large  5.500000   9  7.500000    6
    small  5.500000   9  8.500000    8
foo large  2.000000   5  4.500000    4
    small  2.333333   6  4.333333    2
File:      c:\programdata\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [6]:
data.pivot_table(values = "total_bill" , index = "sex")

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\3655422898.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  data.pivot_table(values = "total_bill" , index = "sex")

        total_bill
sex
Male     20.744076
Female   18.056897

In [7]:
data.pivot_table(values = "tip" , index = "day" , columns = "sex")

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\2501467382.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  data.pivot_table(values = "tip" , index = "day" , columns = "sex")

sex       Male    Female
day
Thur  2.980333  2.575625
Fri   2.693000  2.781111
Sat   3.083898  2.801786
Sun   3.220345  3.367222

In [8]:
df = sns.load_dataset("flights")
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [9]:
df.columns

Index(['year', 'month', 'passengers'], dtype='object')

In [10]:
df.pivot_table(values = "passengers" , index = "year" , columns = "month")

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\3068911307.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values = "passengers" , index = "year" , columns = "month")

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [11]:
df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = True )

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\1030510073.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = True)

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,All
year,,,,,,,,,,,,,
1949,112.00,118.0,132.000000,129.000000,121.000000,135.000000,148.000000,148.000000,136.000000,119.000000,104.000000,118.000000,126.666667
1950,115.00,126.0,141.000000,135.000000,125.000000,149.000000,170.000000,170.000000,158.000000,133.000000,114.000000,140.000000,139.666667
1951,145.00,150.0,178.000000,163.000000,172.000000,178.000000,199.000000,199.000000,184.000000,162.000000,146.000000,166.000000,170.166667
1952,171.00,180.0,193.000000,181.000000,183.000000,218.000000,230.000000,242.000000,209.000000,191.000000,172.000000,194.000000,197.000000
1953,196.00,196.0,236.000000,235.000000,229.000000,243.000000,264.000000,272.000000,237.000000,211.000000,180.000000,201.000000,225.000000
1954,204.00,188.0,235.000000,227.000000,234.000000,264.000000,302.000000,293.000000,259.000000,229.000000,203.000000,229.000000,238.916667
1955,242.00,233.0,267.000000,269.000000,270.000000,315.000000,364.000000,347.000000,312.000000,274.000000,237.000000,278.000000,284.000000
1956,284.00,277.0,317.000000,313.000000,318.000000,374.000000,413.000000,405.000000,355.000000,306.000000,271.000000,306.000000,328.250000
1957,315.00,301.0,356.000000,348.000000,355.000000,422.000000,465.000000,467.000000,404.000000,347.000000,305.000000,336.000000,368.416667
1958,340.00,318.0,362.000000,348.000000,363.000000,435.000000,491.000000,505.000000,404.000000,359.000000,310.000000,337.000000,381.000000
1959,360.00,342.0,406.000000,396.000000,420.000000,472.000000,548.000000,559.000000,463.000000,407.000000,362.000000,405.000000,428.333333
1960,417.00,391.0,419.000000,461.000000,472.000000,535.000000,622.000000,606.000000,508.000000,461.000000,390.000000,432.000000,476.166667
All,241.75,235.0,270.166667,267.083333,271.833333,311.666667,351.333333,351.083333,302.416667,266.583333,232.833333,261.833333,280.298611

In [12]:
df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = True , aggfunc = "sum")

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\2201346191.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = True , aggfunc = "sum")

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,All
year,,,,,,,,,,,,,
1949,112,118,132,129,121,135,148,148,136,119,104,118,1520
1950,115,126,141,135,125,149,170,170,158,133,114,140,1676
1951,145,150,178,163,172,178,199,199,184,162,146,166,2042
1952,171,180,193,181,183,218,230,242,209,191,172,194,2364
1953,196,196,236,235,229,243,264,272,237,211,180,201,2700
1954,204,188,235,227,234,264,302,293,259,229,203,229,2867
1955,242,233,267,269,270,315,364,347,312,274,237,278,3408
1956,284,277,317,313,318,374,413,405,355,306,271,306,3939
1957,315,301,356,348,355,422,465,467,404,347,305,336,4421
1958,340,318,362,348,363,435,491,505,404,359,310,337,4572
1959,360,342,406,396,420,472,548,559,463,407,362,405,5140
1960,417,391,419,461,472,535,622,606,508,461,390,432,5714
All,2901,2820,3242,3205,3262,3740,4216,4213,3629,3199,2794,3142,40363

In [14]:
df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = False )

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\3172335943.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values = "passengers" , index = "year" , columns = "month" , margins = False )

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [15]:
df.pivot_table(values = "passengers" , index = "year" , columns = "month" , aggfunc = "sum")

C:\Users\DELL\AppData\Local\Temp\ipykernel_2064\2284909903.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values = "passengers" , index = "year" , columns = "month" , aggfunc = "sum")

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201
1954   204  188  235  227  234  264  302  293  259  229  203  229
1955   242  233  267  269  270  315  364  347  312  274  237  278
1956   284  277  317  313  318  374  413  405  355  306  271  306
1957   315  301  356  348  355  422  465  467  404  347  305  336
1958   340  318  362  348  363  435  491  505  404  359  310  337
1959   360  342  406  396  420  472  548  559  463  407  362  405
1960   417  391  419  461  472  535  622  606  508  461  390  432

In [18]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
d1 = data.iloc[:100]
d1

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
..         ...   ...     ...    ...  ...     ...   ...
95       40.17  4.73    Male    Yes  Fri  Dinner     4
96       27.28  4.00    Male    Yes  Fri  Dinner     2
97       12.03  1.50    Male    Yes  Fri  Dinner     2
98       21.01  3.00    Male    Yes  Fri  Dinner     2
99       12.46  1.50    Male     No  Fri  Dinner     2

[100 rows x 7 columns]

In [17]:
d2 = data.iloc[100:]
d2

     total_bill   tip     sex smoker   day    time  size
100       11.35  2.50  Female    Yes   Fri  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[144 rows x 7 columns]

In [23]:
pd.concat( (d1 , d2) )  # bydefault axis = 0

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
pd.concat( (d1 , d2) , axis = 1 )

,total_bill,tip,sex,smoker,day,time,size,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.34,1.66,Male,No,Sun,Dinner,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21.01,3.50,Male,No,Sun,Dinner,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23.68,3.31,Male,No,Sun,Dinner,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24.59,3.61,Female,No,Sun,Dinner,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.03,5.92,Male,No,Sat,Dinner,3.0
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.18,2.00,Female,Yes,Sat,Dinner,2.0
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.67,2.00,Male,Yes,Sat,Dinner,2.0
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.82,1.75,Male,No,Sat,Dinner,2.0
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.78,3.00,Female,No,Thur,Dinner,2.0

In [31]:
new_col = np.random.choice(['Good', 'Average', 'Poor'], size=len(data))

In [32]:
new_df = pd.DataFrame(new_col, columns=['rating'])

In [33]:
data_new = pd.concat([data, new_df], axis=1)

In [34]:
data_new

     total_bill   tip     sex smoker   day    time  size   rating
0         16.99  1.01  Female     No   Sun  Dinner     2  Average
1         10.34  1.66    Male     No   Sun  Dinner     3     Poor
2         21.01  3.50    Male     No   Sun  Dinner     3     Poor
3         23.68  3.31    Male     No   Sun  Dinner     2  Average
4         24.59  3.61  Female     No   Sun  Dinner     4     Good
..          ...   ...     ...    ...   ...     ...   ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3     Poor
240       27.18  2.00  Female    Yes   Sat  Dinner     2     Poor
241       22.67  2.00    Male    Yes   Sat  Dinner     2     Good
242       17.82  1.75    Male     No   Sat  Dinner     2  Average
243       18.78  3.00  Female     No  Thur  Dinner     2     Poor

[244 rows x 8 columns]

In [36]:
city = np.random.choice(["Jaipur" , "Noida" , "Delhi"] , 244)
city_df = pd.DataFrame({
    "city" : city
})
city_df

       city
0     Delhi
1     Noida
2    Jaipur
3     Delhi
4     Noida
..      ...
239  Jaipur
240  Jaipur
241  Jaipur
242   Delhi
243   Delhi

[244 rows x 1 columns]

In [37]:
dataa = pd.concat([data , city_df] , axis = 1) 
dataa

     total_bill   tip     sex smoker   day    time  size    city
0         16.99  1.01  Female     No   Sun  Dinner     2   Delhi
1         10.34  1.66    Male     No   Sun  Dinner     3   Noida
2         21.01  3.50    Male     No   Sun  Dinner     3  Jaipur
3         23.68  3.31    Male     No   Sun  Dinner     2   Delhi
4         24.59  3.61  Female     No   Sun  Dinner     4   Noida
..          ...   ...     ...    ...   ...     ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner     3  Jaipur
240       27.18  2.00  Female    Yes   Sat  Dinner     2  Jaipur
241       22.67  2.00    Male    Yes   Sat  Dinner     2  Jaipur
242       17.82  1.75    Male     No   Sat  Dinner     2   Delhi
243       18.78  3.00  Female     No  Thur  Dinner     2   Delhi

[244 rows x 8 columns]

# Merge

In [40]:
# pd.merge()

In [45]:
d1 = pd.DataFrame({
    "marks" : np.random.normal(80 , 10 , 22) ,
    "age" : np.random.normal(20 , 4 , 22) ,
    "roll" : np.arange(1,23)
})
d1

        marks        age  roll
0   92.978674  14.067082     1
1   76.317217  14.683972     2
2   83.037235  21.629603     3
3   53.842600  17.699021     4
4   84.351215  18.133072     5
5   69.062277  14.257990     6
6   83.418982  18.624990     7
7   61.933939  22.535428     8
8   82.418363  24.016085     9
9   89.515811  26.570973    10
10  68.512676  26.368616    11
11  83.753544  11.362710    12
12  78.746313  24.307644    13
13  84.279258  21.053366    14
14  86.594153  19.700007    15
15  73.899594  17.968459    16
16  75.429280  16.610452    17
17  69.531291  16.969842    18
18  71.774259  18.880012    19
19  90.938914  17.171386    20
20  59.689206  23.343934    21
21  75.234754  15.116091    22

In [46]:
d2 = pd.DataFrame({
    "physics_score" : np.random.normal(80 , 10 , 20) ,
    "avg_age" : np.random.normal(20 , 4 , 20) ,
    "roll" : np.arange(1,21)
})
d2

    physics_score    avg_age  roll
0       68.922107  20.201742     1
1       85.895935  15.846280     2
2       72.651589  23.481457     3
3       68.465868  15.599556     4
4       88.410548  21.649431     5
5       85.473981  25.276502     6
6       82.383347  22.702252     7
7       71.894341  22.670372     8
8       95.584681  25.191210     9
9       76.503414  28.765221    10
10      78.247161  19.165867    11
11      82.734868  21.618454    12
12      95.411706  22.004487    13
13      60.425092  21.692826    14
14      75.960235  18.846590    15
15      82.286492  15.785232    16
16      70.992038  15.942447    17
17      86.523048  15.302520    18
18      76.001719  19.532060    19
19      79.308291  15.832127    20

In [49]:
pd.merge(d1 , d2 , on = "roll")  # by default inner join

        marks        age  roll  physics_score    avg_age
0   92.978674  14.067082     1      68.922107  20.201742
1   76.317217  14.683972     2      85.895935  15.846280
2   83.037235  21.629603     3      72.651589  23.481457
3   53.842600  17.699021     4      68.465868  15.599556
4   84.351215  18.133072     5      88.410548  21.649431
5   69.062277  14.257990     6      85.473981  25.276502
6   83.418982  18.624990     7      82.383347  22.702252
7   61.933939  22.535428     8      71.894341  22.670372
8   82.418363  24.016085     9      95.584681  25.191210
9   89.515811  26.570973    10      76.503414  28.765221
10  68.512676  26.368616    11      78.247161  19.165867
11  83.753544  11.362710    12      82.734868  21.618454
12  78.746313  24.307644    13      95.411706  22.004487
13  84.279258  21.053366    14      60.425092  21.692826
14  86.594153  19.700007    15      75.960235  18.846590
15  73.899594  17.968459    16      82.286492  15.785232
16  75.429280  16.610452    17      70.992038  15.942447
17  69.531291  16.969842    18      86.523048  15.302520
18  71.774259  18.880012    19      76.001719  19.532060
19  90.938914  17.171386    20      79.308291  15.832127

In [51]:
pd.date_range?

Signature:
pd.date_range(
    start=None,
    end=None,
    periods=None,
    freq=None,
    tz=None,
    normalize: 'bool' = False,
    name: 'Hashable | None' = None,
    inclusive: 'IntervalClosedType' = 'both',
    *,
    unit: 'str | None' = None,
    **kwargs,
) -> 'DatetimeIndex'
Docstring:
Return a fixed frequency DatetimeIndex.

Returns the range of equally spaced time points (where the difference between any
two adjacent points is specified by the given frequency) such that they all
satisfy `start <[=] x <[=] end`, where the first one and the last one are, resp.,
the first and last time points in that range that fall on the boundary of ``freq``
(if given as a frequency string) or that are valid for ``freq`` (if given as a
:class:`pandas.tseries.offsets.DateOffset`). (If exactly one of ``start``,
``end``, or ``freq`` is *not* specified, this missing parameter can be computed
given ``periods``, the number of timesteps in the range. See the note below.)

Parameters
----------
start : str or datetime-like, optional
    Left bound for generating dates.
end : str or datetime-like, optional
    Right bound for generating dates.
periods : int, optional
    Number of periods to generate.
freq : str, Timedelta, datetime.timedelta, or DateOffset, default 'D'
    Frequency strings can have multiples, e.g. '5h'. See
    :ref:`here <timeseries.offset_aliases>` for a list of
    frequency aliases.
tz : str or tzinfo, optional
    Time zone name for returning localized DatetimeIndex, for example
    'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
    timezone-naive unless timezone-aware datetime-likes are passed.
normalize : bool, default False
    Normalize start/end dates to midnight before generating date range.
name : str, default None
    Name of the resulting DatetimeIndex.
inclusive : {"both", "neither", "left", "right"}, default "both"
    Include boundaries; Whether to set each bound as closed or open.

    .. versionadded:: 1.4.0
unit : str, default None
    Specify the desired resolution of the result.

    .. versionadded:: 2.0.0
**kwargs
    For compatibility. Has no effect on the result.

Returns
-------
DatetimeIndex

See Also
--------
DatetimeIndex : An immutable container for datetimes.
timedelta_range : Return a fixed frequency TimedeltaIndex.
period_range : Return a fixed frequency PeriodIndex.
interval_range : Return a fixed frequency IntervalIndex.

Notes
-----
Of the four parameters ``start``, ``end``, ``periods``, and ``freq``,
exactly three must be specified. If ``freq`` is omitted, the resulting
``DatetimeIndex`` will have ``periods`` linearly spaced elements between
``start`` and ``end`` (closed on both sides).

To learn more about the frequency strings, please see `this link
<https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases>`__.

Examples
--------
**Specifying the values**

The next four examples generate the same `DatetimeIndex`, but vary
the combination of `start`, `end` and `periods`.

Specify `start` and `end`, with the default daily frequency.

>>> pd.date_range(start='1/1/2018', end='1/08/2018')
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

Specify timezone-aware `start` and `end`, with the default daily frequency.

>>> pd.date_range(
...     start=pd.to_datetime("1/1/2018").tz_localize("Europe/Berlin"),
...     end=pd.to_datetime("1/08/2018").tz_localize("Europe/Berlin"),
... )
DatetimeIndex(['2018-01-01 00:00:00+01:00', '2018-01-02 00:00:00+01:00',
               '2018-01-03 00:00:00+01:00', '2018-01-04 00:00:00+01:00',
               '2018-01-05 00:00:00+01:00', '2018-01-06 00:00:00+01:00',
               '2018-01-07 00:00:00+01:00', '2018-01-08 00:00:00+01:00'],
              dtype='datetime64[ns, Europe/Berlin]', freq='D')

Specify `start` and `periods`, the number of periods (days).

>>> pd.date_range(start='1/1/2018', periods=8)
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

Specify `end` and `periods`, the number of periods (days).

>>> pd.date_range(end='1/1/2018', periods=8)
DatetimeIndex(['2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
               '2017-12-29', '2017-12-30', '2017-12-31', '2018-01-01'],
              dtype='datetime64[ns]', freq='D')

Specify `start`, `end`, and `periods`; the frequency is generated
automatically (linearly spaced).

>>> pd.date_range(start='2018-04-24', end='2018-04-27', periods=3)
DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
               '2018-04-27 00:00:00'],
              dtype='datetime64[ns]', freq=None)

**Other Parameters**

Changed the `freq` (frequency) to ``'ME'`` (month end frequency).

>>> pd.date_range(start='1/1/2018', periods=5, freq='ME')
DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31'],
              dtype='datetime64[ns]', freq='ME')

Multiples are allowed

>>> pd.date_range(start='1/1/2018', periods=5, freq='3ME')
DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31'],
              dtype='datetime64[ns]', freq='3ME')

`freq` can also be specified as an Offset object.

>>> pd.date_range(start='1/1/2018', periods=5, freq=pd.offsets.MonthEnd(3))
DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31'],
              dtype='datetime64[ns]', freq='3ME')

Specify `tz` to set the timezone.

>>> pd.date_range(start='1/1/2018', periods=5, tz='Asia/Tokyo')
DatetimeIndex(['2018-01-01 00:00:00+09:00', '2018-01-02 00:00:00+09:00',
               '2018-01-03 00:00:00+09:00', '2018-01-04 00:00:00+09:00',
               '2018-01-05 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Tokyo]', freq='D')

`inclusive` controls whether to include `start` and `end` that are on the
boundary. The default, "both", includes boundary points on either end.

>>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive="both")
DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04'],
              dtype='datetime64[ns]', freq='D')

Use ``inclusive='left'`` to exclude `end` if it falls on the boundary.

>>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive='left')
DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03'],
              dtype='datetime64[ns]', freq='D')

Use ``inclusive='right'`` to exclude `start` if it falls on the boundary, and
similarly ``inclusive='neither'`` will exclude both `start` and `end`.

>>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive='right')
DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04'],
              dtype='datetime64[ns]', freq='D')

**Specify a unit**

>>> pd.date_range(start="2017-01-01", periods=10, freq="100YS", unit="s")
DatetimeIndex(['2017-01-01', '2117-01-01', '2217-01-01', '2317-01-01',
               '2417-01-01', '2517-01-01', '2617-01-01', '2717-01-01',
               '2817-01-01', '2917-01-01'],
              dtype='datetime64[s]', freq='100YS-JAN')
File:      c:\programdata\anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py
Type:      function